#!/system/bin/sh

umask 077

log "Init ssh environment..." 

DSA_KEY=/data/ssh/ssh_host_dsa_key
DSA_PUB_KEY=/data/ssh/ssh_host_dsa_key.pub
RSA_KEY=/data/ssh/ssh_host_rsa_key
RSA_PUB_KEY=/data/ssh/ssh_host_rsa_key.pub
AUTHORIZED_KEYS=/data/.ssh/authorized_keys
OLD_AUTHORIZED_KEYS=/data/ssh/authorized_keys
DEFAULT_AUTHORIZED_KEYS=/system/etc/security/authorized_keys.default

if [ ! -f $DSA_KEY ]; then
    log "Generate DSA key to $DSA_KEY..."
    /system/bin/ssh-keygen -t dsa -f $DSA_KEY -N ""
    chmod 600 /$DSA_KEY
    chmod 644 $DSA_PUB_KEY
fi

if [ ! -f $RSA_KEY ]; then
    log "Generate RSA key to $RSA_KEY..."
    /system/bin/ssh-keygen -t rsa -f $RSA_KEY -N ""
    chmod 600 /$RSA_KEY
    chmod 644 $RSA_PUB_KEY
fi

if [[ -f $OLD_AUTHORIZED_KEYS && ! -f $AUTHORIZED_KEYS ]]; then
    log "Using old authorized keys file..."
    cat $OLD_AUTHORIZED_KEYS > $AUTHORIZED_KEYS
fi

if [[ ! -f $AUTHORIZED_KEYS && -f $DEFAULT_AUTHORIZED_KEYS ]]; then
    log "Using default authorized key file..."
    cat $DEFAULT_AUTHORIZED_KEYS > $AUTHORIZED_KEYS
fi

