#!/system/bin/sh

umask 077

# DEBUG=1

# initialize ssh, then run sshd
init-ssh

if [ "1" == "$DEBUG" ] ; then
    # run sshd in debug mode and capture output to logcat
    log "Starting sshd with logging..."
    /system/bin/logwrapper /system/bin/sshd -f /system/etc/ssh/sshd_config -D -d
else
    # don't daemonize - otherwise we can't stop the sshd service
    log "Starting sshd..."
    /system/bin/sshd -f /system/etc/ssh/sshd_config -D
fi

